function EEG = performICA(EEG)
    EEG = pop_runica(EEG,  ...
                    'icatype', 'runica', ...
                    'extended',1, ...
                    'interrupt','off');
    EEG.icaactivations = EEG.icaweights * EEG.data;

end